In [112]:
import pandas as pd

In [113]:
nyc = pd.read_csv('ave_hi_nyc_jan_1895-2018.csv.xls', header = 'infer')
nyc

Date  Value  Anomaly
0    189501   34.2     -3.2
1    189601   34.7     -2.7
2    189701   35.5     -1.9
3    189801   39.6      2.2
4    189901   36.4     -1.0
..      ...    ...      ...
119  201401   35.5     -1.9
120  201501   36.1     -1.3
121  201601   40.8      3.4
122  201701   42.8      5.4
123  201801   38.7      1.3

[124 rows x 3 columns]

In [114]:
nyc.columns = ['Date', 'Temperature', 'Anomaly']

In [115]:
nyc.head(6)

Date  Temperature  Anomaly
0  189501         34.2     -3.2
1  189601         34.7     -2.7
2  189701         35.5     -1.9
3  189801         39.6      2.2
4  189901         36.4     -1.0
5  190001         37.4      0.0

In [116]:
nyc.tail(6)

Date  Temperature  Anomaly
118  201301         40.8      3.4
119  201401         35.5     -1.9
120  201501         36.1     -1.3
121  201601         40.8      3.4
122  201701         42.8      5.4
123  201801         38.7      1.3

In [117]:
nyc.sample(5)

Date  Temperature  Anomaly
47  194201         36.5     -0.9
19  191401         36.9     -0.5
82  197701         26.1    -11.3
77  197201         40.5      3.1
54  194901         43.5      6.1

In [118]:
nyc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         124 non-null    int64  
 1   Temperature  124 non-null    float64
 2   Anomaly      124 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 3.0 KB


In [119]:
nyc.Date=nyc.Date.floordiv(100)

In [120]:
nyc.head()

Date  Temperature  Anomaly
0  1895         34.2     -3.2
1  1896         34.7     -2.7
2  1897         35.5     -1.9
3  1898         39.6      2.2
4  1899         36.4     -1.0

In [121]:
df = pd.DataFrame({'a':[1.4,2.8,3.9],'b':[4.5, 5.1, 6.9]})
df

a    b
0  1.4  4.5
1  2.8  5.1
2  3.9  6.9

In [122]:
#split for testing training 
from sklearn.model_selection import train_test_split
type(nyc['Date'].values)

numpy.ndarray

In [123]:
nyc['Temperature'].values

array([34.2, 34.7, 35.5, 39.6, 36.4, 37.4, 37. , 35. , 35.5, 29.8, 33.7,
       42.3, 40.5, 38.3, 39.6, 36.1, 40.7, 29.3, 46.9, 36.9, 38.9, 42.3,
       38.4, 26.5, 40.6, 29.7, 39.7, 33.4, 35.2, 39.4, 33.8, 37.2, 36.8,
       40. , 37.8, 38.5, 38.2, 47.6, 45.6, 39.8, 35. , 34.3, 45.7, 37.3,
       36.8, 30. , 34.5, 36.5, 36.1, 39. , 31.5, 40.2, 43. , 30.1, 43.5,
       47.6, 42.5, 42.4, 42.4, 37. , 35.6, 36.2, 33.8, 36.4, 37.1, 37.8,
       31.9, 38. , 34.6, 40.2, 34. , 37.1, 41.6, 31.7, 35.7, 29.9, 31.5,
       40.5, 40.6, 39.7, 41.7, 32.6, 26.1, 32.3, 38.6, 38. , 30.6, 30.9,
       38. , 33.5, 33. , 39.3, 35.9, 34.2, 42.4, 46. , 39.6, 40.9, 41. ,
       31.6, 42.6, 37. , 39.2, 45.8, 40.8, 37.8, 38.8, 45.4, 32.9, 31. ,
       37.4, 47.6, 43.6, 42.4, 33.4, 38.1, 34.8, 44.2, 40.8, 35.5, 36.1,
       40.8, 42.8, 38.7])

In [124]:
import numpy as np

In [125]:
m=np.linspace(1,5,10)
m

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [126]:
m.shape

(10,)

In [127]:
#spliting for trainin and testing 

In [128]:
#50:50 ratio 
X_train, X_test, y_train, y_test = train_test_split(nyc.Date.values.reshape(-1, 1), nyc.Temperature.values, test_size=0.50, random_state=11)

In [129]:
#80:20
#X_train, X_test, y_train, y_test = train_test_split(nyc.Date.values.reshape(-1, 1), nyc.Temperature.values, test_size=0.20, random_state=11)


In [130]:
#90:10
#X_train_90, X_test_90, y_train_90, y_test_90 = train_test_split(nyc.Date.values.reshape(-1, 1), nyc.Temperature.values, test_size=0.10, random_state=11)


In [131]:
#75:25
#X_train_75, X_test_75, y_train_75, y_test_75 = train_test_split(nyc.Date.values.reshape(-1, 1), nyc.Temperature.values, test_size=0.25, random_state=11)


In [132]:
X_train.shape

(62, 1)

In [133]:
X_test.shape

(62, 1)

In [134]:
25+99

124

In [135]:
99/124*100

79.83870967741935

In [136]:
31/124*100

25.0

In [137]:
X_train[0]

array([1991], dtype=int64)

In [138]:
y_train[0]

39.6

In [139]:
from sklearn.linear_model import LinearRegression

In [140]:
linear_regression = LinearRegression()

In [141]:
linear_regression.fit(X=X_train, y=y_train)

LinearRegression()

In [142]:
linear_regression.coef_

array([0.01259279])

In [143]:
linear_regression.intercept_

12.294840201266386

In [144]:
#model output
predicted= linear_regression.predict(X=X_test)

In [145]:
expected = y_test

In [146]:
predicted

array([37.0774579 , 36.18336956, 37.12782907, 36.27151911, 36.35966867,
       37.61894802, 36.15818397, 36.61152454, 36.92634438, 36.86338041,
       36.52337498, 37.37968495, 36.64930292, 37.4678345 , 36.23374073,
       36.6870813 , 37.29153539, 37.10264349, 37.2663498 , 37.58116964,
       37.20338584, 36.53596778, 36.59893175, 36.97671555, 36.34707587,
       36.93893717, 36.888566  , 37.24116422, 36.43522543, 36.42263264,
       36.4855966 , 37.43005612, 36.77523086, 37.63154082, 36.51078219,
       36.80041644, 37.69450478, 37.50561288, 37.68191199, 36.83819482,
       36.91375158, 36.41003984, 37.40487053, 36.98930835, 36.81300924,
       37.48042729, 36.2967047 , 36.67448851, 36.54856057, 37.44264891,
       37.60635523, 37.49302009, 37.02708673, 37.14042187, 37.41746333,
       37.35449936, 36.73745247, 36.75004527, 37.25375701, 37.55598406,
       36.38485426, 37.32931377])

In [147]:
expected

array([31.7, 35.5, 40.5, 29.8, 40.7, 34.8, 34.2, 38.2, 36.2, 42.5, 39.4,
       40.9, 39.8, 40.8, 37. , 45.7, 33. , 29.9, 38. , 42.4, 32.3, 33.8,
       38.5, 37.8, 36.1, 33.8, 42.4, 30.6, 38.4, 42.3, 39.7, 37. , 39. ,
       44.2, 35.2, 40.2, 42.8, 45.4, 40.8, 43.5, 35.6, 38.9, 31.6, 31.9,
       43. , 37.8, 42.3, 34.3, 37.2, 39.2, 38.1, 38.8, 40.2, 40.6, 42.6,
       46. , 34.5, 36.5, 30.9, 47.6, 46.9, 34.2])

In [148]:
#testing the model

In [149]:
predict = (lambda date: linear_regression.coef_ * date + linear_regresion.interept_)

In [150]:
def computerTemp(date):
    return linear_regression.coef_*date +linear_regression.intercept_

In [151]:
computerTemp(2024)

array([37.78265434])

In [158]:
linear_regression.fit(X_train, y_train)
predictions = linear_regression.predict(X_test)

In [160]:
predictions

array([37.0774579 , 36.18336956, 37.12782907, 36.27151911, 36.35966867,
       37.61894802, 36.15818397, 36.61152454, 36.92634438, 36.86338041,
       36.52337498, 37.37968495, 36.64930292, 37.4678345 , 36.23374073,
       36.6870813 , 37.29153539, 37.10264349, 37.2663498 , 37.58116964,
       37.20338584, 36.53596778, 36.59893175, 36.97671555, 36.34707587,
       36.93893717, 36.888566  , 37.24116422, 36.43522543, 36.42263264,
       36.4855966 , 37.43005612, 36.77523086, 37.63154082, 36.51078219,
       36.80041644, 37.69450478, 37.50561288, 37.68191199, 36.83819482,
       36.91375158, 36.41003984, 37.40487053, 36.98930835, 36.81300924,
       37.48042729, 36.2967047 , 36.67448851, 36.54856057, 37.44264891,
       37.60635523, 37.49302009, 37.02708673, 37.14042187, 37.41746333,
       37.35449936, 36.73745247, 36.75004527, 37.25375701, 37.55598406,
       36.38485426, 37.32931377])

In [161]:
#rmse
from sklearn.metrics import mean_squared_error

In [163]:
rmse= np.sqrt(mean_squared_error(y_test, predictions))

In [164]:
rmse

4.547268305790129